server:
  port: 12345

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

logging:
  file:
    path: res/logs
  level:
    org.springframework: warn
    com.example.myapp: debug

res:
  upload: /home/raymond/project/SoftMetric/res/upload

